### ISSUE TITLE
Let's not use ++

### ISSUE THREAD

**Issue by madvas** [district0x/streamtide-smart-contract#2]
Please  let's use explicit notation for incrementing, in the whole codebase, such as `i = i + 1` , as it's much clearer in intention

https://github.com/district0x/streamtide-smart-contract/blob/c5fb22f9354eba2b3d769b313b66fd14255a3533/streamtide.sol#L89

**Comment by danshinn89** [comment]
updated. Please verify if I missed any variables still using ++
