### ISSUE TITLE
Round in closed after date expires

### ISSUE THREAD

**Issue by madvas** [district0x/streamtide-smart-contract#3]
Instead of having bool `roundOpen` to determine if round is ongoing, we could do just with `roundStart` and `roundDuration`. 
Function `roundIsClosed` would return true after the `roundStart` + `roundDuration` > now. And if we want to be able to explicitely close the round, we can have `closeRound` function which just sets `roundDuration` to 0. There's no real need to maintain `roundOpen` bool variable. 

https://github.com/district0x/streamtide-smart-contract/blob/c5fb22f9354eba2b3d769b313b66fd14255a3533/streamtide.sol#L60

**Comment by danshinn89** [comment]
Removed unnecessary modifier and included roundIsClosed function that checks the above. Added require statement to make sure round is closed before distribute function will run
