### ISSUE TITLE
Donate function shouldn't be restricted to `roundIsOpen `

### ISSUE THREAD

**Issue by madvas** [district0x/streamtide-smart-contract#4]
Obviously you still have this in progress, just leaving it here so we don't forget. Donating should be possible no matter if matching round is open or closed. 

https://github.com/district0x/streamtide-smart-contract/blob/c5fb22f9354eba2b3d769b313b66fd14255a3533/streamtide.sol#L92

**Comment by danshinn89** [comment]
removed modifier and require statement. Donations are available anytime
