### ISSUE TITLE
Function to remove admin as well

### ISSUE THREAD

**Issue by madvas** [district0x/streamtide-smart-contract#6]
Additionally to `addAdmin` we should have `removeAdmin` where owner can remove admin priviledges. 

https://github.com/district0x/streamtide-smart-contract/blob/ad9471f94ca6d7e1be18f38cd0177f3b52ed96cf/streamtide.sol#L63

**Comment by danshinn89** [comment]
Added please check and approve

**Comment by danshinn89** [comment]
In addition, should I include a function to add and to remove blacklisted addresses?

**Comment by madvas** [comment]
yeah that's probably good idea as well

**Comment by danshinn89** [comment]
blacklist function added. Please check
